package edu.tsi1.gr5.crazyfinger.entity;

// Generated 03-oct-2009 15:52:18 by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;

import javax.persistence.DiscriminatorValue;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Alojamiento generated by hbm2java
 */
@Entity
@Table(name = "alojamiento")
@DiscriminatorValue("hotel")
public class Alojamiento extends Servicio implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5339578453786078570L;
	
	private Set<Estadia> estadias = new HashSet<Estadia>(0);

	public String toString(){
		return getNombre()+" costo por dia: U$S"+getCosto();
	}
	
	public Alojamiento() {
	}

	public Alojamiento(long idAlojamiento, double costodia) {
		super();
	}

	public Alojamiento(long idAlojamiento, 
			Set<Estadia> estadias) {
		super();
		this.estadias = estadias;
	}


	@OneToMany(fetch = FetchType.LAZY, mappedBy = "alojamiento")
	public Set<Estadia> getEstadias() {
		return this.estadias;
	}

	public void setEstadias(Set<Estadia> estadias) {
		this.estadias = estadias;
	}

}
