package edu.tsi1.gr5.crazyfinger.entity;

// Generated 03-oct-2009 15:52:18 by Hibernate Tools 3.2.4.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import org.hibernate.validator.NotNull;

/**
 * Calificacion generated by hbm2java
 */
@Entity
@Table(name = "calificacion")
public class Calificacion implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6061655007568881759L;
	
	private long idCalificacion;
	private Usuario usuario;
	private Servicio servicio;
	private Integer puntaje;
	private String comentario;

	public Calificacion() {
	}

	public Calificacion(long idCalificacion, Usuario usuario) {
		this.idCalificacion = idCalificacion;
		this.usuario = usuario;
	}

	public Calificacion(long idCalificacion, Usuario usuario,
			Servicio servicio, Integer puntaje, String comentario) {
		this.idCalificacion = idCalificacion;
		this.usuario = usuario;
		this.servicio = servicio;
		this.puntaje = puntaje;
		this.comentario = comentario;
	}

	@GeneratedValue
	@Id
	@Column(name = "id_calificacion", unique = true, nullable = false)
	public long getIdCalificacion() {
		return this.idCalificacion;
	}

	public void setIdCalificacion(long idCalificacion) {
		this.idCalificacion = idCalificacion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "usuario", nullable = false)
	@NotNull
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "servicio")
	public Servicio getServicio() {
		return this.servicio;
	}

	public void setServicio(Servicio servicio) {
		this.servicio = servicio;
	}

	@Column(name = "puntaje")
	public Integer getPuntaje() {
		return this.puntaje;
	}

	public void setPuntaje(Integer puntaje) {
		this.puntaje = puntaje;
	}

	@Column(name = "comentario")
	public String getComentario() {
		return this.comentario;
	}

	public void setComentario(String comentario) {
		this.comentario = comentario;
	}

}
