package edu.tsi1.gr5.crazyfinger.entity;

// Generated 03-oct-2009 15:52:18 by Hibernate Tools 3.2.4.GA

import java.text.SimpleDateFormat;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import org.hibernate.validator.NotNull;

import edu.tsi1.gr5.crazyfinger.helper.FechasHelper;
import edu.tsi1.gr5.crazyfinger.media.entity.Media;

/**
 * Comentario generated by hbm2java
 */
@Entity
@Table(name = "comentario")
public class Comentario implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8400158418561277271L;
	
	private long idComentario;
	private Usuario usuario;
	private String mensaje;
	private Media media;
	private Date fechaEnviado;

	public Comentario() {
	}

	public Comentario(long idComentario, Usuario usuario, String mensaje) {
		this.idComentario = idComentario;
		this.usuario = usuario;
		this.mensaje = mensaje;
	}

	@GeneratedValue
	@Id
	@Column(name = "id_comentario", unique = true, nullable = false)
	public long getIdComentario() {
		return this.idComentario;
	}

	public void setIdComentario(long idComentario) {
		this.idComentario = idComentario;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "usuario", nullable = false)
	@NotNull
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	@Column(name = "mensaje", nullable = false)
	@NotNull
	public String getMensaje() {
		return this.mensaje;
	}

	public void setMensaje(String mensaje) {
		this.mensaje = mensaje;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "media")
	public Media getMedia() {
		return this.media;
	}

	public void setMedia(Media media) {
		this.media = media;
	}
	
	@Column(name = "fechaenviado",nullable = false)
	public Date getFechaEnviado() {
		return fechaEnviado;
	}

	public void setFechaEnviado(Date fechaEnviado) {
		this.fechaEnviado = fechaEnviado;
	}
	
	public String fechaEnviadoFormato(){
		return FechasHelper.getInstance().fechaEnviadoFormato(fechaEnviado);
	}
}
