package edu.tsi1.gr5.crazyfinger.entity;

// Generated 03-oct-2009 15:52:18 by Hibernate Tools 3.2.4.GA

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import org.hibernate.validator.NotNull;

/**
 * Mail generated by hbm2java
 */
@Entity
@Table(name = "mail")
public class Mail implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7284587478308433644L;
	
	public static int ESTADO_INICIAL = 1;
	public static int ESTADO_LEIDO = 2;
	
	private long idMail;
	private Usuario usuarioByDestinatario;
	private Usuario usuarioByRemitente;
	private String mensaje;
	private int estado = 0;
	private Date fechaEnviado;
	private long idDestinatario;
	private long idRemitente;

	public Mail() {
	}

	public Mail(long idMail, Usuario usuarioByDestinatario,
			Usuario usuarioByRemitente, String mensaje, int estado) {
		this.idMail = idMail;
		this.usuarioByDestinatario = usuarioByDestinatario;
		this.usuarioByRemitente = usuarioByRemitente;
		this.mensaje = mensaje;
		this.estado = estado;
	}

	@GeneratedValue
	@Id
	@Column(name = "id_mail", unique = true, nullable = false)
	public long getIdMail() {
		return this.idMail;
	}

	public void setIdMail(long idMail) {
		this.idMail = idMail;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "destinatario", nullable = false)
	@NotNull
	public Usuario getUsuarioByDestinatario() {
		return this.usuarioByDestinatario;
	}

	public void setUsuarioByDestinatario(Usuario usuarioByDestinatario) {
		setIdDestinatario(usuarioByDestinatario.getIdUsuario());
		this.usuarioByDestinatario = usuarioByDestinatario;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "remitente", nullable = false)
	@NotNull
	public Usuario getUsuarioByRemitente() {
		return this.usuarioByRemitente;
	}

	public void setUsuarioByRemitente(Usuario usuarioByRemitente) {
		setIdRemitente(usuarioByRemitente.getIdUsuario());
		this.usuarioByRemitente = usuarioByRemitente;
	}

	@Column(name = "mensaje", nullable = false)
	@NotNull
	public String getMensaje() {
		return this.mensaje;
	}

	public void setMensaje(String mensaje) {
		this.mensaje = mensaje;
	}

	@Column(name = "estado", nullable = false)
	public int getEstado() {
		return this.estado;
	}

	public void setEstado(int estado) {
		this.estado = estado;
	}

	@Column(name = "fechaenviado",nullable = false)
	public Date getFechaEnviado() {
		return fechaEnviado;
	}

	public void setFechaEnviado(Date fechaEnviado) {
		this.fechaEnviado = fechaEnviado;
	}

	@Column(name = "iddestinatario", nullable = false)
	@NotNull
	public long getIdDestinatario() {
		return idDestinatario;
	}

	public void setIdDestinatario(long idDestinatario) {
		this.idDestinatario = idDestinatario;
	}

	@Column(name = "idremitente", nullable = false)
	@NotNull
	public long getIdRemitente() {
		return idRemitente;
	}

	public void setIdRemitente(long idRemitente) {
		this.idRemitente = idRemitente;
	}

}
