package edu.tsi1.gr5.crazyfinger.entity;

// Generated 03-oct-2009 15:52:18 by Hibernate Tools 3.2.4.GA

import javax.persistence.DiscriminatorValue;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.validator.NotNull;

/**
 * Nodopv generated by hbm2java
 */
@Entity
@Table(name = "nodopv")
@DiscriminatorValue("2")
public class Nodopv extends Nodo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1799087189216012203L;
	
	private Proyectoviaje proyectoviaje;
	

	public Nodopv() {
	}

	public Nodopv(long idNodopv, Proyectoviaje proyectoviaje) {
		super();
		this.proyectoviaje = proyectoviaje;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "proyectoviaje", nullable = false)
	@NotNull
	public Proyectoviaje getProyectoviaje() {
		return this.proyectoviaje;
	}

	public void setProyectoviaje(Proyectoviaje proyectoviaje) {
		this.proyectoviaje = proyectoviaje;
	}

}
