package edu.tsi1.gr5.crazyfinger.entity;

// Generated 03-oct-2009 15:52:18 by Hibernate Tools 3.2.4.GA

import javax.persistence.DiscriminatorValue;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.validator.NotNull;

/**
 * Nodopt generated by hbm2java
 */
@Entity
@Table(name = "nodopt")
@DiscriminatorValue("1")
public class Nodopt extends Nodo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3829036333046876220L;
	
	private Paqueteturistico paqueteturistico;

	public Nodopt() {
	}

	public Nodopt(long idNodopt, Paqueteturistico paqueteturistico) {
		super();
		this.paqueteturistico = paqueteturistico;
	}


	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "paqueteturistico", nullable = false)
	@NotNull
	public Paqueteturistico getPaqueteturistico() {
		return this.paqueteturistico;
	}

	public void setPaqueteturistico(Paqueteturistico paqueteturistico) {
		this.paqueteturistico = paqueteturistico;
	}

}
