package edu.tsi1.gr5.crazyfinger.entity;

// Generated 03-oct-2009 15:52:18 by Hibernate Tools 3.2.4.GA

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Paqueteturistico generated by hbm2java
 */
@Entity
@Table(name = "paqueteturistico")
public class Paqueteturistico implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 3569788131212240977L;
	
	public static int ESTADO_EDICION = 0;
	public static int ESTADO_HABILITADO = 1;
	public static int ESTADO_ANULADO = 2;
	
	private long idPaqueteturistico;
	private String nombre;
	private String descripcion;
	private int estado;
	private Set<Nodopt> nodopts = new HashSet<Nodopt>(0);

	public Paqueteturistico() {
	}

	public Paqueteturistico(long idPaqueteturistico, String nombre, int estado) {
		this.idPaqueteturistico = idPaqueteturistico;
		this.nombre = nombre;
		this.estado = estado;
	}

	public Paqueteturistico(long idPaqueteturistico, String nombre, int estado,
			Set<Nodopt> nodopts) {
		this.idPaqueteturistico = idPaqueteturistico;
		this.nombre = nombre;
		this.estado = estado;
		this.nodopts = nodopts;
	}

	@Id
	@GeneratedValue
	@Column(name = "id_paqueteturistico", unique = true, nullable = false)
	public long getIdPaqueteturistico() {
		return this.idPaqueteturistico;
	}

	public void setIdPaqueteturistico(long idPaqueteturistico) {
		this.idPaqueteturistico = idPaqueteturistico;
	}

	@Column(name = "nombre", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "estado", nullable = false)
	public int getEstado() {
		return this.estado;
	}

	public void setEstado(int estado) {
		this.estado = estado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "paqueteturistico")
	public Set<Nodopt> getNodopts() {
		return this.nodopts;
	}

	public void setNodopts(Set<Nodopt> nodopts) {
		this.nodopts = nodopts;
	}

	@Column(name = "descripcion", nullable = false, length = 300)
	@NotNull
	@Length(max = 300)
	public String getDescripcion() {
		return descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public String textoEstado(){
		if(estado == Paqueteturistico.ESTADO_ANULADO)
			return "Anulado";
		if(estado == Paqueteturistico.ESTADO_EDICION)
			return "Edicion";
		if(estado == Paqueteturistico.ESTADO_HABILITADO)
			return "Habilitado";
		return "";
	}
	
	public List<Nodopt> listaNodos(){
		if(nodopts != null)
			if(nodopts.size() > 0)
				return new ArrayList<Nodopt>(nodopts);
			else
				return new ArrayList<Nodopt>();
		return null;
	}
}
