package edu.tsi1.gr5.crazyfinger.entity;

// Generated 03-oct-2009 15:52:18 by Hibernate Tools 3.2.4.GA

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

import edu.tsi1.gr5.crazyfinger.helper.FechasHelper;

/**
 * Pasaje generated by hbm2java
 */
@Entity
@Table(name = "pasaje")
public class Pasaje implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2775845983729793833L;
	
	private long idPasaje;
	private Traslado traslado;
	private String fecha;

	public Pasaje() {
	}

	public Pasaje(long idPasaje, Traslado traslado) {
		this.idPasaje = idPasaje;
		this.traslado = traslado;
	}

	public Pasaje(long idPasaje, Traslado traslado, Nodo nodo, String fecha) {
		this.idPasaje = idPasaje;
		this.traslado = traslado;
		this.fecha = fecha;
	}

	@GeneratedValue
	@Id
	@Column(name = "id_pasaje", unique = true, nullable = false)
	public long getIdPasaje() {
		return this.idPasaje;
	}

	public void setIdPasaje(long idPasaje) {
		this.idPasaje = idPasaje;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "traslado", nullable = false)
	@NotNull
	public Traslado getTraslado() {
		return this.traslado;
	}

	public void setTraslado(Traslado traslado) {
		this.traslado = traslado;
	}

	@Column(name = "fecha", length = 50)
	@Length(max = 50)
	public String getFecha() {
		return this.fecha;
	}

	public void setFecha(String fecha) {
		this.fecha = fecha;
	}
	
	public String getFechaConFormato(String formato) {
		return FechasHelper.getInstance().fechaConFormato(new Date(fecha), formato);
	}

}
