package edu.tsi1.gr5.crazyfinger.entity;

// Generated 03-oct-2009 15:52:18 by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Puntoturistico generated by hbm2java
 */
@Entity
@Table(name = "puntoturistico")
public class Puntoturistico implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8178088914706068667L;
	
	private long idPuntoturistico;
	private Lugar lugar;
	private String nombre;
	private String detalle;
	private Double latitud;
	private Double longitud;
	private Set<Actividad> actividades = new HashSet<Actividad>(0);

	public Puntoturistico() {
	}

	public Puntoturistico(long idPuntoturistico, String nombre) {
		this.idPuntoturistico = idPuntoturistico;
		this.nombre = nombre;
	}

	public Puntoturistico(long idPuntoturistico, Lugar lugar, String nombre,
			String detalle, Double latitud, Double longitud,
			Set<Actividad> actividades) {
		this.idPuntoturistico = idPuntoturistico;
		this.lugar = lugar;
		this.nombre = nombre;
		this.detalle = detalle;
		this.latitud = latitud;
		this.longitud = longitud;
		this.actividades = actividades;
	}

	@GeneratedValue
	@Id
	@Column(name = "id_puntoturistico", unique = true, nullable = false)
	public long getIdPuntoturistico() {
		return this.idPuntoturistico;
	}

	public void setIdPuntoturistico(long idPuntoturistico) {
		this.idPuntoturistico = idPuntoturistico;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "lugar")
	public Lugar getLugar() {
		return this.lugar;
	}

	public void setLugar(Lugar lugar) {
		this.lugar = lugar;
	}

	@Column(name = "nombre", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "detalle")
	public String getDetalle() {
		return this.detalle;
	}

	public void setDetalle(String detalle) {
		this.detalle = detalle;
	}

	@Column(name = "latitud", precision = 17, scale = 17)
	public Double getLatitud() {
		return this.latitud;
	}

	public void setLatitud(Double latitud) {
		this.latitud = latitud;
	}

	@Column(name = "longitud", precision = 17, scale = 17)
	public Double getLongitud() {
		return this.longitud;
	}

	public void setLongitud(Double longitud) {
		this.longitud = longitud;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "puntoturistico")
	public Set<Actividad> getActividades() {
		return this.actividades;
	}

	public void setActividades(Set<Actividad> actividades) {
		this.actividades = actividades;
	}

}
