package edu.tsi1.gr5.crazyfinger.entity;

// Generated 03-oct-2009 15:52:18 by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.DiscriminatorColumn;
import javax.persistence.DiscriminatorType;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Servicio generated by hbm2java
 */
@Entity
@Table(name = "servicio")
@Inheritance(strategy=InheritanceType.JOINED)
@DiscriminatorColumn(name="tipo",discriminatorType=DiscriminatorType.STRING)
public class Servicio implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -70512617698354409L;
	
	private long idServicio;
	private Lugar lugar;
	private String tipo;
	private String nombre;
	private String url;
	private Double costo;
	private Set<Calificacion> calificacions = new HashSet<Calificacion>(0);

	public Servicio() {
	}

	public Servicio(long idServicio, Lugar lugar, String tipo, String nombre) {
		this.idServicio = idServicio;
		this.lugar = lugar;
		this.tipo = tipo;
		this.nombre = nombre;
	}

	public Servicio(long idServicio, Lugar lugar, String tipo, String nombre,
			Double costo, Set<Calificacion> calificacions) {
		this.idServicio = idServicio;
		this.lugar = lugar;
		this.tipo = tipo;
		this.nombre = nombre;
		this.costo = costo;
		this.calificacions = calificacions;
	}

	@GeneratedValue
	@Id
	@Column(name = "id_servicio", unique = true, nullable = false)
	public long getIdServicio() {
		return this.idServicio;
	}

	public void setIdServicio(long idServicio) {
		this.idServicio = idServicio;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "lugar", nullable = false)
	@NotNull
	public Lugar getLugar() {
		return this.lugar;
	}

	public void setLugar(Lugar lugar) {
		this.lugar = lugar;
	}

	@Column(name = "tipo", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	@Column(name = "nombre", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "url", nullable = true, length = 250)
	@NotNull
	@Length(max = 250)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}
	
	@Column(name = "costo", precision = 17, scale = 17)
	public Double getCosto() {
		return this.costo;
	}

	public void setCosto(Double costo) {
		this.costo = costo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "servicio")
	public Set<Calificacion> getCalificacions() {
		return this.calificacions;
	}

	public void setCalificacions(Set<Calificacion> calificacions) {
		this.calificacions = calificacions;
	}

	
	
}
