package edu.tsi1.gr5.crazyfinger.entity;

// Generated 03-oct-2009 15:52:18 by Hibernate Tools 3.2.4.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import org.hibernate.validator.NotNull;

/**
 * Solicitud generated by hbm2java
 */
@Entity
@Table(name = "solicitud")
public class Solicitud implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6951081029670684669L;
	
	
	public static final int ESTADO_PENDIENTE = 0;
    public static final int ESTADO_ACEPTADO = 1;
	
	private long idsolicitud;
	private Usuario usuarioBySolicitante;
	private Usuario usuarioBySolicitado;
	private String mensaje;
	private int estado;
	private long idSolicitante;
	private long idSolicitado;

	public Solicitud() {
	}

	public Solicitud(long idsolicitud, Usuario usuarioBySolicitante,
			Usuario usuarioBySolicitado) {
		this.idsolicitud = idsolicitud;
		this.usuarioBySolicitante = usuarioBySolicitante;
		this.usuarioBySolicitado = usuarioBySolicitado;
	}

	public Solicitud(long idsolicitud, Usuario usuarioBySolicitante,
			Usuario usuarioBySolicitado, String mensaje) {
		this.idsolicitud = idsolicitud;
		this.usuarioBySolicitante = usuarioBySolicitante;
		this.usuarioBySolicitado = usuarioBySolicitado;
		this.mensaje = mensaje;
	}

	@GeneratedValue
	@Id
	@Column(name = "id_solicitud", unique = true, nullable = false)
	public long getIdsolicitud() {
		return this.idsolicitud;
	}

	public void setIdsolicitud(long idsolicitud) {
		this.idsolicitud = idsolicitud;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "solicitante", nullable = false)
	@NotNull
	public Usuario getUsuarioBySolicitante() {
		return this.usuarioBySolicitante;
	}

	public void setUsuarioBySolicitante(Usuario usuarioBySolicitante) {
		setIdSolicitante(usuarioBySolicitante.getIdUsuario());
		this.usuarioBySolicitante = usuarioBySolicitante;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "solicitado", nullable = false)
	@NotNull
	public Usuario getUsuarioBySolicitado() {
		return this.usuarioBySolicitado;
	}

	public void setUsuarioBySolicitado(Usuario usuarioBySolicitado) {
		setIdSolicitado(usuarioBySolicitado.getIdUsuario());
		this.usuarioBySolicitado = usuarioBySolicitado;
	}

	@Column(name = "mensaje")
	public String getMensaje() {
		return this.mensaje;
	}

	public void setMensaje(String mensaje) {
		this.mensaje = mensaje;
	}
	
	@Column(name = "estado", nullable = false)
	public int getEstado() {
		return this.estado;
	}

	public void setEstado(int estado) {
		this.estado = estado;
	}

	public String textoEstado(){
		if(estado == ESTADO_ACEPTADO)
			return "Aceptado";
		else
			return "Pendiente";
	}

	@Column(name = "idsolicitante", nullable = false)
	@NotNull
	public long getIdSolicitante() {
		return idSolicitante;
	}

	public void setIdSolicitante(long idSolicitante) {
		this.idSolicitante = idSolicitante;
	}

	@Column(name = "idsolicitado", nullable = false)
	@NotNull
	public long getIdSolicitado() {
		return idSolicitado;
	}

	public void setIdSolicitado(long idSolicitado) {
		this.idSolicitado = idSolicitado;
	}
	
}
