//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3074
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 2.0.5.0
// 
namespace SilverCloud.ServiceReferenceSilver {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Etiqueta", Namespace="http://schemas.datacontract.org/2004/07/ArmazonGr6")]
    public partial class Etiqueta : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string NombreField;
        
        private long TamanioField;
        
        private string UrlField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Tamanio {
            get {
                return this.TamanioField;
            }
            set {
                if ((this.TamanioField.Equals(value) != true)) {
                    this.TamanioField = value;
                    this.RaisePropertyChanged("Tamanio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Url {
            get {
                return this.UrlField;
            }
            set {
                if ((object.ReferenceEquals(this.UrlField, value) != true)) {
                    this.UrlField = value;
                    this.RaisePropertyChanged("Url");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="", ConfigurationName="ServiceReferenceSilver.ServiceSilver")]
    public interface ServiceSilver {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:ServiceSilver/GetCloudItems", ReplyAction="urn:ServiceSilver/GetCloudItemsResponse")]
        System.IAsyncResult BeginGetCloudItems(System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<SilverCloud.ServiceReferenceSilver.Etiqueta> EndGetCloudItems(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:ServiceSilver/Redireccionar", ReplyAction="urn:ServiceSilver/RedireccionarResponse")]
        System.IAsyncResult BeginRedireccionar(string nombreEtiqueta, System.AsyncCallback callback, object asyncState);
        
        void EndRedireccionar(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface ServiceSilverChannel : SilverCloud.ServiceReferenceSilver.ServiceSilver, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class GetCloudItemsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetCloudItemsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<SilverCloud.ServiceReferenceSilver.Etiqueta> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<SilverCloud.ServiceReferenceSilver.Etiqueta>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class ServiceSilverClient : System.ServiceModel.ClientBase<SilverCloud.ServiceReferenceSilver.ServiceSilver>, SilverCloud.ServiceReferenceSilver.ServiceSilver {
        
        private BeginOperationDelegate onBeginGetCloudItemsDelegate;
        
        private EndOperationDelegate onEndGetCloudItemsDelegate;
        
        private System.Threading.SendOrPostCallback onGetCloudItemsCompletedDelegate;
        
        private BeginOperationDelegate onBeginRedireccionarDelegate;
        
        private EndOperationDelegate onEndRedireccionarDelegate;
        
        private System.Threading.SendOrPostCallback onRedireccionarCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public ServiceSilverClient() {
        }
        
        public ServiceSilverClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSilverClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSilverClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSilverClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<GetCloudItemsCompletedEventArgs> GetCloudItemsCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> RedireccionarCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult SilverCloud.ServiceReferenceSilver.ServiceSilver.BeginGetCloudItems(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetCloudItems(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<SilverCloud.ServiceReferenceSilver.Etiqueta> SilverCloud.ServiceReferenceSilver.ServiceSilver.EndGetCloudItems(System.IAsyncResult result) {
            return base.Channel.EndGetCloudItems(result);
        }
        
        private System.IAsyncResult OnBeginGetCloudItems(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((SilverCloud.ServiceReferenceSilver.ServiceSilver)(this)).BeginGetCloudItems(callback, asyncState);
        }
        
        private object[] OnEndGetCloudItems(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<SilverCloud.ServiceReferenceSilver.Etiqueta> retVal = ((SilverCloud.ServiceReferenceSilver.ServiceSilver)(this)).EndGetCloudItems(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetCloudItemsCompleted(object state) {
            if ((this.GetCloudItemsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetCloudItemsCompleted(this, new GetCloudItemsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetCloudItemsAsync() {
            this.GetCloudItemsAsync(null);
        }
        
        public void GetCloudItemsAsync(object userState) {
            if ((this.onBeginGetCloudItemsDelegate == null)) {
                this.onBeginGetCloudItemsDelegate = new BeginOperationDelegate(this.OnBeginGetCloudItems);
            }
            if ((this.onEndGetCloudItemsDelegate == null)) {
                this.onEndGetCloudItemsDelegate = new EndOperationDelegate(this.OnEndGetCloudItems);
            }
            if ((this.onGetCloudItemsCompletedDelegate == null)) {
                this.onGetCloudItemsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetCloudItemsCompleted);
            }
            base.InvokeAsync(this.onBeginGetCloudItemsDelegate, null, this.onEndGetCloudItemsDelegate, this.onGetCloudItemsCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult SilverCloud.ServiceReferenceSilver.ServiceSilver.BeginRedireccionar(string nombreEtiqueta, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginRedireccionar(nombreEtiqueta, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void SilverCloud.ServiceReferenceSilver.ServiceSilver.EndRedireccionar(System.IAsyncResult result) {
            base.Channel.EndRedireccionar(result);
        }
        
        private System.IAsyncResult OnBeginRedireccionar(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string nombreEtiqueta = ((string)(inValues[0]));
            return ((SilverCloud.ServiceReferenceSilver.ServiceSilver)(this)).BeginRedireccionar(nombreEtiqueta, callback, asyncState);
        }
        
        private object[] OnEndRedireccionar(System.IAsyncResult result) {
            ((SilverCloud.ServiceReferenceSilver.ServiceSilver)(this)).EndRedireccionar(result);
            return null;
        }
        
        private void OnRedireccionarCompleted(object state) {
            if ((this.RedireccionarCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.RedireccionarCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void RedireccionarAsync(string nombreEtiqueta) {
            this.RedireccionarAsync(nombreEtiqueta, null);
        }
        
        public void RedireccionarAsync(string nombreEtiqueta, object userState) {
            if ((this.onBeginRedireccionarDelegate == null)) {
                this.onBeginRedireccionarDelegate = new BeginOperationDelegate(this.OnBeginRedireccionar);
            }
            if ((this.onEndRedireccionarDelegate == null)) {
                this.onEndRedireccionarDelegate = new EndOperationDelegate(this.OnEndRedireccionar);
            }
            if ((this.onRedireccionarCompletedDelegate == null)) {
                this.onRedireccionarCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnRedireccionarCompleted);
            }
            base.InvokeAsync(this.onBeginRedireccionarDelegate, new object[] {
                        nombreEtiqueta}, this.onEndRedireccionarDelegate, this.onRedireccionarCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override SilverCloud.ServiceReferenceSilver.ServiceSilver CreateChannel() {
            return new ServiceSilverClientChannel(this);
        }
        
        private class ServiceSilverClientChannel : ChannelBase<SilverCloud.ServiceReferenceSilver.ServiceSilver>, SilverCloud.ServiceReferenceSilver.ServiceSilver {
            
            public ServiceSilverClientChannel(System.ServiceModel.ClientBase<SilverCloud.ServiceReferenceSilver.ServiceSilver> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginGetCloudItems(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("GetCloudItems", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<SilverCloud.ServiceReferenceSilver.Etiqueta> EndGetCloudItems(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<SilverCloud.ServiceReferenceSilver.Etiqueta> _result = ((System.Collections.ObjectModel.ObservableCollection<SilverCloud.ServiceReferenceSilver.Etiqueta>)(base.EndInvoke("GetCloudItems", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginRedireccionar(string nombreEtiqueta, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = nombreEtiqueta;
                System.IAsyncResult _result = base.BeginInvoke("Redireccionar", _args, callback, asyncState);
                return _result;
            }
            
            public void EndRedireccionar(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("Redireccionar", _args, result);
            }
        }
    }
}
