package edu.tsi1.gr5.crazyfinger.entity;

// Generated 03-oct-2009 15:52:18 by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Actividad generated by hbm2java
 */
@Entity
@Table(name = "actividad")
public class Actividad implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6195018310232474565L;
	
	private long idActividad;
	private Lugar lugar;
	private Puntoturistico puntoturistico;
	private String nombre;
	private String url;
	private String tipo;
	private String detalle;
	private Double latitud;
	private Double longitud;
	private Set<Nodo> nodos = new HashSet<Nodo>(0);
	

	public String toString(){
		return getNombre()+"\n"+getDetalle();
	}

	public Actividad() {
	}

	public Actividad(long idActividad, Lugar lugar, String nombre) {
		this.idActividad = idActividad;
		this.lugar = lugar;
		this.nombre = nombre;
	}

	public Actividad(long idActividad, Lugar lugar,
			Puntoturistico puntoturistico, String nombre, String tipo,
			String detalle, Double latitud, Double longitud, Set<Nodo> nodos) {
		this.idActividad = idActividad;
		this.lugar = lugar;
		this.puntoturistico = puntoturistico;
		this.nombre = nombre;
		this.tipo = tipo;
		this.detalle = detalle;
		this.latitud = latitud;
		this.longitud = longitud;
		this.nodos=nodos;
	}

	@GeneratedValue
	@Id
	@Column(name = "id_actividad", unique = true, nullable = false)
	public long getIdActividad() {
		return this.idActividad;
	}

	public void setIdActividad(long idActividad) {
		this.idActividad = idActividad;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "lugar", nullable = false)
	@NotNull
	public Lugar getLugar() {
		return this.lugar;
	}

	public void setLugar(Lugar lugar) {
		this.lugar = lugar;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "puntoturistico")
	public Puntoturistico getPuntoturistico() {
		return this.puntoturistico;
	}

	public void setPuntoturistico(Puntoturistico puntoturistico) {
		this.puntoturistico = puntoturistico;
	}

	@Column(name = "nombre", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}
	
	
	@Column(name = "url", nullable = true, length = 250)
	@NotNull
	@Length(max = 250)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Column(name = "tipo", length = 50)
	@Length(max = 50)
	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	@Column(name = "detalle")
	public String getDetalle() {
		return this.detalle;
	}

	public void setDetalle(String detalle) {
		this.detalle = detalle;
	}

	@Column(name = "latitud", precision = 17, scale = 17)
	public Double getLatitud() {
		return this.latitud;
	}

	public void setLatitud(Double latitud) {
		this.latitud = latitud;
	}

	@Column(name = "longitud", precision = 17, scale = 17)
	public Double getLongitud() {
		return this.longitud;
	}

	public void setLongitud(Double longitud) {
		this.longitud = longitud;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "actividad_nodo", joinColumns = @JoinColumn(name = "id_actividad"), inverseJoinColumns = @JoinColumn(name = "id_nodo"))
	public Set<Nodo> getNodos() {
		return this.nodos;
	}

	public void setNodos(Set<Nodo> nodos) {
		this.nodos = nodos;
	}
	
}
