package edu.tsi1.gr5.crazyfinger.entity;

// Generated 03-oct-2009 15:52:18 by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.validator.NotNull;

/**
 * Estadia generated by hbm2java
 */
@Entity
@Table(name = "estadia")
public class Estadia implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6936006545815714703L;
	
	private long idEstadia;
	private Nodo nodo;
	private Alojamiento alojamiento;
	private Date fechaDesde;
	private Date fechaHasta;
	private double costototal;
	private Set<Nodo> nodos = new HashSet<Nodo>(0);

	public Estadia() {
	}

	public Estadia(long idEstadia, Alojamiento alojamiento, double costototal) {
		this.idEstadia = idEstadia;
		this.alojamiento = alojamiento;
		this.costototal = costototal;
	}

	public Estadia(long idEstadia, Nodo nodo, Alojamiento alojamiento,
			Date fechaDesde,Date fechaHasta, double costototal, Set<Nodo> nodos) {
		this.idEstadia = idEstadia;
		this.nodo = nodo;
		this.alojamiento = alojamiento;
		this.fechaDesde = fechaDesde;
		this.fechaHasta = fechaHasta;
		this.costototal = costototal;
		this.nodos = nodos;
	}

	@GeneratedValue
	@Id
	@Column(name = "id_estadia", unique = true, nullable = false)
	public long getIdEstadia() {
		return this.idEstadia;
	}

	public void setIdEstadia(long idEstadia) {
		this.idEstadia = idEstadia;
	}

	@OneToOne(fetch = FetchType.LAZY , mappedBy="estadia")
	public Nodo getNodo() {
		return this.nodo;
	}

	public void setNodo(Nodo nodo) {
		this.nodo = nodo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "alojamiento", nullable = false)
	@NotNull
	public Alojamiento getAlojamiento() {
		return this.alojamiento;
	}

	public void setAlojamiento(Alojamiento alojamiento) {
		this.alojamiento = alojamiento;
	}

	@Column(name = "fechadesde")
	public Date getFechaDesde() {
		return this.fechaDesde;
	}

	public void setFechaDesde(Date fecha) {
		this.fechaDesde = fecha;
	}
	
	@Column(name = "fechahasta")
	public Date getFechaHasta() {
		return this.fechaHasta;
	}

	public void setFechaHasta(Date fecha) {
		this.fechaHasta = fecha;
	}

	@Column(name = "costototal", nullable = false, precision = 17, scale = 17)
	public double getCostototal() {
		return this.costototal;
	}

	public void setCostototal(double costototal) {
		this.costototal = costototal;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "estadia")
	public Set<Nodo> getNodos() {
		return this.nodos;
	}

	public void setNodos(Set<Nodo> nodos) {
		this.nodos = nodos;
	}

	public void calcularCosto() {
		long milPerDay = 1000*60*60*24; 
		long dias = (fechaHasta.getTime()-fechaDesde.getTime()) / milPerDay;
		costototal = dias*alojamiento.getCosto();		
	}

}
