package edu.tsi1.gr5.crazyfinger.entity;

// Generated 03-oct-2009 15:52:18 by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;
import org.jboss.seam.annotations.Name;

import edu.tsi1.gr5.crazyfinger.media.entity.Media;


/**
 * Lugar generated by hbm2java
 */
@Entity
@Table(name = "lugar")
public class Lugar implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5635071655727856403L;
	
	private long idLugar;
	private String nombre;
	private String pais;
	private double latitud;
	private double longitud;
	private String url;
	private Set<Actividad> actividades = new HashSet<Actividad>(0);
	private Set<Traslado> trasladosForOrigen = new HashSet<Traslado>(0);
	private Set<Servicio> servicios = new HashSet<Servicio>(0);
	private Set<Puntoturistico> puntoturisticos = new HashSet<Puntoturistico>(0);
	private Set<Traslado> trasladosForDestino = new HashSet<Traslado>(0);
	private Set<Media> medias = new HashSet<Media>(0);
	private Set<Nodo> nodos = new HashSet<Nodo>(0);

	public Lugar() {
	}
/*
	public Lugar(long idLugar, String nombre, double latitud, double longitud) {
		this.idLugar = idLugar;
		this.nombre = nombre;
		this.latitud = latitud;
		this.longitud = longitud;
	}
*/	 
	public Lugar(long idLugar, String nombre, String pais, double latitud, double longitud) {
		this.idLugar = idLugar;
		this.nombre = nombre;
		this.latitud = latitud;
		this.longitud = longitud;
		this.pais=pais;
	}
/*
	public Lugar(long idLugar, String nombre, double latitud, double longitud,
			String url, Set<Actividad> actividades,
			Set<Traslado> trasladosForOrigen, Set<Servicio> servicios,
			Set<Puntoturistico> puntoturisticos,
			Set<Traslado> trasladosForDestino, Set<Media> medias) {
		this.idLugar = idLugar;
		this.nombre = nombre;
		this.latitud = latitud;
		this.longitud = longitud;
		this.url = url;
		this.actividades = actividades;
		this.trasladosForOrigen = trasladosForOrigen;
		this.servicios = servicios;
		this.puntoturisticos = puntoturisticos;
		this.trasladosForDestino = trasladosForDestino;
		this.medias = medias;
	}
*/
	public Lugar(long idLugar, String nombre, String pais, double latitud, double longitud,
			String url, Set<Actividad> actividades,
			Set<Traslado> trasladosForOrigen, Set<Servicio> servicios,
			Set<Puntoturistico> puntoturisticos,
			Set<Traslado> trasladosForDestino, Set<Media> medias) {
		this.idLugar = idLugar;
		this.nombre = nombre;
		this.latitud = latitud;
		this.longitud = longitud;
		this.url = url;
		this.actividades = actividades;
		this.trasladosForOrigen = trasladosForOrigen;
		this.servicios = servicios;
		this.puntoturisticos = puntoturisticos;
		this.trasladosForDestino = trasladosForDestino;
		this.medias = medias;
		this.pais=pais;
	}
	
	@GeneratedValue
	@Id
	@Column(name = "id_lugar", unique = true, nullable = false)
	public long getIdLugar() {
		return this.idLugar;
	}

	public void setIdLugar(long idLugar) {
		this.idLugar = idLugar;
	}

	@Column(name = "nombre", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}
	
	@Column(name = "pais", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getPais() {
		return this.pais;
	}

	public void setPais(String pais) {
		this.pais = pais;
	}

	@Column(name = "latitud", nullable = false, precision = 17, scale = 17)
	public double getLatitud() {
		return this.latitud;
	}

	public void setLatitud(double latitud) {
		this.latitud = latitud;
	}

	@Column(name = "longitud", nullable = false, precision = 17, scale = 17)
	public double getLongitud() {
		return this.longitud;
	}

	public void setLongitud(double longitud) {
		this.longitud = longitud;
	}

	@Column(name = "url", length = 250)
	@Length(max = 250)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "lugar")
	public Set<Actividad> getActividades() {
		return this.actividades;
	}

	public void setActividades(Set<Actividad> actividades) {
		this.actividades = actividades;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "lugarByOrigen")
	public Set<Traslado> getTrasladosForOrigen() {
		return this.trasladosForOrigen;
	}

	public void setTrasladosForOrigen(Set<Traslado> trasladosForOrigen) {
		this.trasladosForOrigen = trasladosForOrigen;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "lugar")
	public Set<Servicio> getServicios() {
		return this.servicios;
	}

	public void setServicios(Set<Servicio> servicios) {
		this.servicios = servicios;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "lugar")
	public Set<Puntoturistico> getPuntoturisticos() {
		return this.puntoturisticos;
	}

	public void setPuntoturisticos(Set<Puntoturistico> puntoturisticos) {
		this.puntoturisticos = puntoturisticos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "lugarByDestino")
	public Set<Traslado> getTrasladosForDestino() {
		return this.trasladosForDestino;
	}

	public void setTrasladosForDestino(Set<Traslado> trasladosForDestino) {
		this.trasladosForDestino = trasladosForDestino;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "lugar")
	public Set<Media> getMedias() {
		return this.medias;
	}

	public void setMedias(Set<Media> medias) {
		this.medias = medias;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "lugar")
	public Set<Nodo> getNodos() {
		return this.nodos;
	}

	public void setNodos(Set<Nodo> nodos) {
		this.nodos = nodos;
	}

}
