package edu.tsi1.gr5.crazyfinger.entity;

// Generated 03-oct-2009 15:52:18 by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.DiscriminatorColumn;
import javax.persistence.DiscriminatorType;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * Nodo generated by hbm2java
 */
@Entity
@Table(name = "nodo")
@Inheritance(strategy=InheritanceType.JOINED)
@DiscriminatorColumn(name="tipoNodo",discriminatorType=DiscriminatorType.INTEGER)
public class Nodo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1245863823577882759L;
	
	public static int TIPO_NODO_PT = 1;
	public static int TIPO_NODO_PV = 2;
	
	private long idNodo;
	private long orden;
	private Estadia estadia;
	private int estado;
	private int tipoNodo;

	private Pasaje pasajeSalida;
	private Pasaje pasajeLlegada;
	private Lugar lugar;
	
	private Set<Actividad> actividades = new HashSet<Actividad>(0);

	public Nodo() {
	}

	public Nodo(long idNodo, int estado ,long orden) {
		this.idNodo = idNodo;
		this.estado = estado;
		this.orden = orden;
	}

	public Nodo(long idNodo, Estadia estadia, int estado,long orden) {
		this.idNodo = idNodo;
		this.estadia = estadia;
		this.estado = estado;
		this.orden = orden;
	}

	@GeneratedValue
	@Id
	@Column(name = "id_nodo", unique = true, nullable = false)
	public long getIdNodo() {
		return this.idNodo;
	}

	public void setIdNodo(long idNodo) {
		this.idNodo = idNodo;
	}

	@OneToOne(fetch = FetchType.LAZY)
	public Estadia getEstadia() {
		return this.estadia;
	}

	public void setEstadia(Estadia estadia) {
		this.estadia = estadia;
	}

	@Column(name = "estado", nullable = false)
	public int getEstado() {
		return this.estado;
	}

	public void setEstado(int estado) {
		this.estado = estado;
	}
	
	@Column(name = "orden", nullable = false)
	public long getOrden() {
		return this.orden;
	}

	public void setOrden(long orden) {
		this.orden = orden;
	}

	
	@OneToOne
	public Pasaje getPasajeSalida() {
		return this.pasajeSalida;
	}

	public void setPasajeSalida(Pasaje pasaje) {
		this.pasajeSalida = pasaje;
	}
	
	@OneToOne
	public Pasaje getPasajeLlegada() {
		return this.pasajeLlegada;
	}

	public void setPasajeLlegada(Pasaje pasaje) {
		this.pasajeLlegada = pasaje;
	}
	
	

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "actividad_nodo", joinColumns = @JoinColumn(name = "id_nodo"), inverseJoinColumns = @JoinColumn(name = "id_actividad"))
	public Set<Actividad> getNodos() {
		return this.actividades;
	}

	public void setNodos(Set<Actividad> actividades) {
		this.actividades = actividades;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "lugar")
	public Lugar getLugar() {
		return lugar;
	}

	public void setLugar(Lugar lugar) {
		this.lugar = lugar;
	}

	public int getTipoNodo() {
		return tipoNodo;
	}

	public void setTipoNodo(int tipoNodo) {
		this.tipoNodo = tipoNodo;
	}

	public double costoTotalNodo(){
		double costo = 0;
		costo += estadia.getCostototal();
		costo += pasajeLlegada.getTraslado().getCosto();
		if(pasajeSalida != null)
			costo += pasajeSalida.getTraslado().getCosto();
		return costo;
	}

	
	
}
