package edu.tsi1.gr5.crazyfinger.entity;

// Generated 03-oct-2009 15:52:18 by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Traslado generated by hbm2java
 */
@Entity
@Table(name = "traslado")
public class Traslado implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8298422374005599790L;
	
	private long idTraslado;
	private Lugar lugarByOrigen;
	private Lugar lugarByDestino;
	private String horario;
	private String empresa;
	private Double costo;
	//private String tipo;
	private Mediotransporte mediotransporte ;
	private Set<Pasaje> pasajes = new HashSet<Pasaje>(0);
	private long idLugarByOrigen;
	private long idLugarByDestino;

	public Traslado() {
	}

	public String toString(){
		return empresa+" "+horario+" "+costo+" "+lugarByDestino.getNombre();
	}
/*	
	public String urlImagen(){
		if(tipo.equalsIgnoreCase("avion"))
			return "/img/silueta_avion.jpg";
		if(tipo.equalsIgnoreCase("tren"))
			return "/img/silueta_tren.jpg";
		if(tipo.equalsIgnoreCase("barco"))
			return "/img/silueta_barco.jpg";
		return "";
	}
*/
	public String urlImagen(){
		return mediotransporte.getUrl();
	}
	public Traslado(long idTraslado, Lugar lugarByOrigen,
			Lugar lugarByDestino/*, String tipo*/) {
		this.idTraslado = idTraslado;
		this.lugarByOrigen = lugarByOrigen;
		this.lugarByDestino = lugarByDestino;
		//this.tipo = tipo;
		this.idLugarByOrigen=lugarByOrigen.getIdLugar();
		this.idLugarByDestino=lugarByDestino.getIdLugar();
	}

	public Traslado(long idTraslado, Lugar lugarByOrigen,
			Lugar lugarByDestino, String horario, String empresa, Double costo,
			/*String tipo,*/ Set<Pasaje> pasajes) {
		this.idTraslado = idTraslado;
		this.lugarByOrigen = lugarByOrigen;
		this.lugarByDestino = lugarByDestino;
		this.horario = horario;
		this.empresa = empresa;
		this.costo = costo;
		//this.tipo = tipo;
		this.pasajes = pasajes;
		this.idLugarByOrigen=lugarByOrigen.getIdLugar();
		this.idLugarByDestino=lugarByDestino.getIdLugar();
	}

	@GeneratedValue
	@Id
	@Column(name = "id_traslado", unique = true, nullable = false)
	public long getIdTraslado() {
		return this.idTraslado;
	}

	public void setIdTraslado(long idTraslado) {
		this.idTraslado = idTraslado;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "origen", nullable = false)
	@NotNull
	public Lugar getLugarByOrigen() {
		return this.lugarByOrigen;
	}

	public void setLugarByOrigen(Lugar lugarByOrigen) {
		this.lugarByOrigen = lugarByOrigen;
		this.idLugarByOrigen=lugarByOrigen.getIdLugar();
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "destino", nullable = false)
	@NotNull
	public Lugar getLugarByDestino() {
		return this.lugarByDestino;
	}

	public void setLugarByDestino(Lugar lugarByDestino) {
		this.lugarByDestino = lugarByDestino;
		this.idLugarByDestino=lugarByDestino.getIdLugar();
	}

	@Column(name = "horario", length = 50)
	@Length(max = 50)
	public String getHorario() {
		return this.horario;
	}

	public void setHorario(String horario) {
		this.horario = horario;
	}

	@Column(name = "empresa")
	public String getEmpresa() {
		return this.empresa;
	}

	public void setEmpresa(String empresa) {
		this.empresa = empresa;
	}

	@Column(name = "costo", precision = 17, scale = 17)
	public Double getCosto() {
		return this.costo;
	}

	public void setCosto(Double costo) {
		this.costo = costo;
	}
/*
	@Column(name = "tipo", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}
*/
	
	@OneToOne(fetch = FetchType.LAZY)
	public Mediotransporte getMediotransporte() {
		return this.mediotransporte;
	}

	public void setMediotransporte(Mediotransporte mediotransporte) {
		this.mediotransporte = mediotransporte;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "traslado")
	public Set<Pasaje> getPasajes() {
		return this.pasajes;
	}

	public void setPasajes(Set<Pasaje> pasajes) {
		this.pasajes = pasajes;
	}

	public long getIdLugarByOrigen() {
		return idLugarByOrigen;
	}

	public void setIdLugarByOrigen(long idLugarByOrigen) {
		this.idLugarByOrigen = idLugarByOrigen;
	}

	public long getIdLugarByDestino() {
		return idLugarByDestino;
	}

	public void setIdLugarByDestino(long idLugarByDestino) {
		this.idLugarByDestino = idLugarByDestino;
	}

}
