//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArmazonGr6.Client_Armazon {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DCProduct", Namespace="http://schemas.datacontract.org/2004/07/Armazon.DataContracts")]
    [System.SerializableAttribute()]
    public partial class DCProduct : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ArmazonGr6.Client_Armazon.DCProductAttr[] AttrsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProductIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float RatingAvgField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ArmazonGr6.Client_Armazon.DCProductAttr[] Attrs {
            get {
                return this.AttrsField;
            }
            set {
                if ((object.ReferenceEquals(this.AttrsField, value) != true)) {
                    this.AttrsField = value;
                    this.RaisePropertyChanged("Attrs");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductId {
            get {
                return this.ProductIdField;
            }
            set {
                if ((this.ProductIdField.Equals(value) != true)) {
                    this.ProductIdField = value;
                    this.RaisePropertyChanged("ProductId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float RatingAvg {
            get {
                return this.RatingAvgField;
            }
            set {
                if ((this.RatingAvgField.Equals(value) != true)) {
                    this.RatingAvgField = value;
                    this.RaisePropertyChanged("RatingAvg");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DCProductAttr", Namespace="http://schemas.datacontract.org/2004/07/Armazon.DataContracts")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ArmazonGr6.Client_Armazon.DCProductAttrDouble))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ArmazonGr6.Client_Armazon.DCProductAttrString))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ArmazonGr6.Client_Armazon.DCProductAttrFloat))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ArmazonGr6.Client_Armazon.DCProductAttrBool))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ArmazonGr6.Client_Armazon.DCProductAttrInt))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ArmazonGr6.Client_Armazon.DCProductAttrImage))]
    public partial class DCProductAttr : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsKeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsKey {
            get {
                return this.IsKeyField;
            }
            set {
                if ((this.IsKeyField.Equals(value) != true)) {
                    this.IsKeyField = value;
                    this.RaisePropertyChanged("IsKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DCProductAttrDouble", Namespace="http://schemas.datacontract.org/2004/07/Armazon.DataContracts")]
    [System.SerializableAttribute()]
    public partial class DCProductAttrDouble : ArmazonGr6.Client_Armazon.DCProductAttr {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Value {
            get {
                return this.ValueField;
            }
            set {
                if ((this.ValueField.Equals(value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DCProductAttrString", Namespace="http://schemas.datacontract.org/2004/07/Armazon.DataContracts")]
    [System.SerializableAttribute()]
    public partial class DCProductAttrString : ArmazonGr6.Client_Armazon.DCProductAttr {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DCProductAttrFloat", Namespace="http://schemas.datacontract.org/2004/07/Armazon.DataContracts")]
    [System.SerializableAttribute()]
    public partial class DCProductAttrFloat : ArmazonGr6.Client_Armazon.DCProductAttr {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float Value {
            get {
                return this.ValueField;
            }
            set {
                if ((this.ValueField.Equals(value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DCProductAttrBool", Namespace="http://schemas.datacontract.org/2004/07/Armazon.DataContracts")]
    [System.SerializableAttribute()]
    public partial class DCProductAttrBool : ArmazonGr6.Client_Armazon.DCProductAttr {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Value {
            get {
                return this.ValueField;
            }
            set {
                if ((this.ValueField.Equals(value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DCProductAttrInt", Namespace="http://schemas.datacontract.org/2004/07/Armazon.DataContracts")]
    [System.SerializableAttribute()]
    public partial class DCProductAttrInt : ArmazonGr6.Client_Armazon.DCProductAttr {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Value {
            get {
                return this.ValueField;
            }
            set {
                if ((this.ValueField.Equals(value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DCProductAttrImage", Namespace="http://schemas.datacontract.org/2004/07/Armazon.DataContracts")]
    [System.SerializableAttribute()]
    public partial class DCProductAttrImage : ArmazonGr6.Client_Armazon.DCProductAttr {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UrlField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Url {
            get {
                return this.UrlField;
            }
            set {
                if ((object.ReferenceEquals(this.UrlField, value) != true)) {
                    this.UrlField = value;
                    this.RaisePropertyChanged("Url");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DCRating", Namespace="http://schemas.datacontract.org/2004/07/Armazon.DataContracts")]
    [System.SerializableAttribute()]
    public partial class DCRating : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CommentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RatingField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Comment {
            get {
                return this.CommentField;
            }
            set {
                if ((object.ReferenceEquals(this.CommentField, value) != true)) {
                    this.CommentField = value;
                    this.RaisePropertyChanged("Comment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Rating {
            get {
                return this.RatingField;
            }
            set {
                if ((this.RatingField.Equals(value) != true)) {
                    this.RatingField = value;
                    this.RaisePropertyChanged("Rating");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DCCartItem", Namespace="http://schemas.datacontract.org/2004/07/Armazon.DataContracts")]
    [System.SerializableAttribute()]
    public partial class DCCartItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProductIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuantityField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductId {
            get {
                return this.ProductIdField;
            }
            set {
                if ((this.ProductIdField.Equals(value) != true)) {
                    this.ProductIdField = value;
                    this.RaisePropertyChanged("ProductId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Client_Armazon.IArmazonWS")]
    public interface IArmazonWS {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IArmazonWS/search", ReplyAction="http://tempuri.org/IArmazonWS/searchResponse")]
        ArmazonGr6.Client_Armazon.DCProduct[] search(string fullText);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IArmazonWS/getProduct", ReplyAction="http://tempuri.org/IArmazonWS/getProductResponse")]
        ArmazonGr6.Client_Armazon.DCProduct getProduct(int idProduct);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IArmazonWS/getRatings", ReplyAction="http://tempuri.org/IArmazonWS/getRatingsResponse")]
        ArmazonGr6.Client_Armazon.DCRating[] getRatings(int idProduct);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IArmazonWS/CartBuy", ReplyAction="http://tempuri.org/IArmazonWS/CartBuyResponse")]
        bool CartBuy(string user, ArmazonGr6.Client_Armazon.DCCartItem[] items);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface IArmazonWSChannel : ArmazonGr6.Client_Armazon.IArmazonWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class ArmazonWSClient : System.ServiceModel.ClientBase<ArmazonGr6.Client_Armazon.IArmazonWS>, ArmazonGr6.Client_Armazon.IArmazonWS {
        
        public ArmazonWSClient() {
        }
        
        public ArmazonWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ArmazonWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ArmazonWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ArmazonWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ArmazonGr6.Client_Armazon.DCProduct[] search(string fullText) {
            return base.Channel.search(fullText);
        }
        
        public ArmazonGr6.Client_Armazon.DCProduct getProduct(int idProduct) {
            return base.Channel.getProduct(idProduct);
        }
        
        public ArmazonGr6.Client_Armazon.DCRating[] getRatings(int idProduct) {
            return base.Channel.getRatings(idProduct);
        }
        
        public bool CartBuy(string user, ArmazonGr6.Client_Armazon.DCCartItem[] items) {
            return base.Channel.CartBuy(user, items);
        }
    }
}
