// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JSR-172 Reference Implementation wscompile 1.0, using: JAX-RPC Standard Implementation (1.1, build R59)

package edu.tsi3.scrumme.cel.net;


public class ArrayOfLong {
    protected java.lang.Long[] _long;
    
    public ArrayOfLong() {
    }
    
    public ArrayOfLong(java.lang.Long[] _long) {
        this._long = _long;
    }
    
    public java.lang.Long[] get_long() {
        return _long;
    }
    
    public void set_long(java.lang.Long[] _long) {
        this._long = _long;
    }
}
