// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JSR-172 Reference Implementation wscompile 1.0, using: JAX-RPC Standard Implementation (1.1, build R59)

package edu.tsi3.scrumme.cel.net;


public class LoginResponse {
    protected java.lang.Long out;
    
    public LoginResponse() {
    }
    
    public LoginResponse(java.lang.Long out) {
        this.out = out;
    }
    
    public java.lang.Long getOut() {
        return out;
    }
    
    public void setOut(java.lang.Long out) {
        this.out = out;
    }
}
