// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JSR-172 Reference Implementation wscompile 1.0, using: JAX-RPC Standard Implementation (1.1, build R59)

package edu.tsi3.scrumme.cel.net;


public class ProyectosAsignado {
    protected java.lang.Long in0;
    
    public ProyectosAsignado() {
    }
    
    public ProyectosAsignado(java.lang.Long in0) {
        this.in0 = in0;
    }
    
    public java.lang.Long getIn0() {
        return in0;
    }
    
    public void setIn0(java.lang.Long in0) {
        this.in0 = in0;
    }
}
