// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JSR-172 Reference Implementation wscompile 1.0, using: JAX-RPC Standard Implementation (1.1, build R59)

package edu.tsi3.scrumme.cel.net;


public class ProyectosAsignadoResponse {
    protected edu.tsi3.scrumme.cel.net.ArrayOfLong out;
    
    public ProyectosAsignadoResponse() {
    }
    
    public ProyectosAsignadoResponse(edu.tsi3.scrumme.cel.net.ArrayOfLong out) {
        this.out = out;
    }
    
    public edu.tsi3.scrumme.cel.net.ArrayOfLong getOut() {
        return out;
    }
    
    public void setOut(edu.tsi3.scrumme.cel.net.ArrayOfLong out) {
        this.out = out;
    }
}
