// This class was generated by 172 StubGenerator.
// Contents subject to change without notice.
// @generated

package edu.tsi3.scrumme.cel.net;

public interface Web_PortType extends java.rmi.Remote {
	public edu.tsi3.scrumme.cel.net.ArrayOfLong proyectosAsignado(java.lang.Long in0) throws java.rmi.RemoteException;

	public java.lang.String nombreProyecto(java.lang.Long in0) throws java.rmi.RemoteException;

	public java.lang.Long login(java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException;

}
