#created on: 28/05/2011
package edu.tsig.wms.router.rules

import org.jboss.soa.esb.message.Message;
import org.jboss.soa.esb.message.format.MessageType;
import org.jboss.soa.esb.http.HttpRequest;

#declare any global variables here
global java.util.List destinations;

rule "GetRequest"
	when
		msg : Message()
	then
		HttpRequest request = HttpRequest.getRequest(msg);
		insert(request);
end

rule "GetFeatureInfo"
	when
		HttpRequest(queryParams['REQUEST'][0] == "GetFeatureInfo")
	then
		destinations.add("soap");
end

rule "Otros"
	when
		HttpRequest(queryParams['REQUEST'][0] != "GetFeatureInfo")
	then
		destinations.add("rest");
end
