<?xml version="1.0" encoding="utf-8"?>
<Database Name="ArmazonBD" Class="ArmazonModelDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.\SQLEXPRESS;AttachDbFilename=|DataDirectory|\ArmazonBD.mdf;Integrated Security=True;User Instance=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="ArmazonBDConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Clientes" Member="Clientes">
    <Type Name="Cliente">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="idCarritoActual" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Cliente_Calificacion" Member="Calificacions" ThisKey="id" OtherKey="idCliente" Type="Calificacion" />
      <Association Name="Cliente_HistoricoCarrito" Member="HistoricoCarritos" ThisKey="id" OtherKey="idCliente" Type="HistoricoCarrito" />
      <Association Name="Usuario_Cliente" Member="Usuario" ThisKey="id" OtherKey="id" Type="Usuario" IsForeignKey="true" />
      <Association Name="Carrito_Cliente" Member="Carrito" ThisKey="idCarritoActual" OtherKey="id" Type="Carrito" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ArtCants" Member="ArtCants">
    <Type Name="ArtCant">
      <Column Name="idCarrito" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="idArticulo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="cantidad" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Association Name="Articulo_ArtCant" Member="Articulo" ThisKey="idArticulo" OtherKey="id" Type="Articulo" IsForeignKey="true" />
      <Association Name="Carrito_ArtCant" Member="Carrito" ThisKey="idCarrito" OtherKey="id" Type="Carrito" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Plantillas" Member="Plantillas">
    <Type Name="Plantilla">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="NChar(15) NOT NULL" CanBeNull="false" />
      <Association Name="Plantilla_FormaPago" Member="FormaPagos" ThisKey="id" OtherKey="idPlantilla" Type="FormaPago" />
      <Association Name="Plantilla_Campo" Member="Campos" ThisKey="id" OtherKey="idPlantilla" Type="Campo" />
      <Association Name="Plantilla_Categoria" Member="Categorias" ThisKey="id" OtherKey="idPlantilla" Type="Categoria" />
    </Type>
  </Table>
  <Table Name="dbo.Registros" Member="Registros">
    <Type Name="Registro">
      <Column Name="idCampo" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="idArticulo" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="valor" Type="System.String" DbType="NChar(300)" CanBeNull="true" />
      <Association Name="Articulo_Registro" Member="Articulo" ThisKey="idArticulo" OtherKey="id" Type="Articulo" IsForeignKey="true" />
      <Association Name="Campo_Registro" Member="Campo" ThisKey="idCampo" OtherKey="id" Type="Campo" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.FormaPagos" Member="FormaPagos">
    <Type Name="FormaPago">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="NChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="idPlantilla" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="imgUrl" Type="System.String" DbType="NChar(256)" CanBeNull="true" />
      <Association Name="FormaPago_Carrito" Member="Carritos" ThisKey="id" OtherKey="idFormaPago" Type="Carrito" />
      <Association Name="Plantilla_FormaPago" Member="Plantilla" ThisKey="idPlantilla" OtherKey="id" Type="Plantilla" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Calificacions" Member="Calificacions">
    <Type Name="Calificacion">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="puntuacion" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="revision" Type="System.String" DbType="NChar(350)" CanBeNull="true" />
      <Column Name="idCliente" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="idArticulo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Cliente_Calificacion" Member="Cliente" ThisKey="idCliente" OtherKey="id" Type="Cliente" IsForeignKey="true" />
      <Association Name="Articulo_Calificacion" Member="Articulo" ThisKey="idArticulo" OtherKey="id" Type="Articulo" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Internos" Member="Internos">
    <Type Name="Interno">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Articulo_Interno" Member="Articulo" ThisKey="id" OtherKey="id" Type="Articulo" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Externos" Member="Externos">
    <Type Name="Externo">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="claveExterna" Type="System.String" DbType="NChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="idProveedor" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Proveedor_Externo" Member="Proveedor" ThisKey="idProveedor" OtherKey="id" Type="Proveedor" IsForeignKey="true" />
      <Association Name="Articulo_Externo" Member="Articulo" ThisKey="id" OtherKey="id" Type="Articulo" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Proveedors" Member="Proveedors">
    <Type Name="Proveedor">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="NChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="url" Type="System.String" DbType="NChar(250) NOT NULL" CanBeNull="false" />
      <Association Name="Proveedor_Externo" Member="Externos" ThisKey="id" OtherKey="idProveedor" Type="Externo" />
    </Type>
  </Table>
  <Table Name="dbo.Sucursals" Member="Sucursals">
    <Type Name="Sucursal">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="NChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="direccion" Type="System.String" DbType="NChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="telefono" Type="System.String" DbType="NChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ciudad" Type="System.String" DbType="NChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="latitud" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="longitud" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.HistoricoCarritos" Member="HistoricoCarritos">
    <Type Name="HistoricoCarrito">
      <Column Name="idCliente" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="idCarrito" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Cliente_HistoricoCarrito" Member="Cliente" ThisKey="idCliente" OtherKey="id" Type="Cliente" IsForeignKey="true" />
      <Association Name="Carrito_HistoricoCarrito" Member="Carrito" ThisKey="idCarrito" OtherKey="id" Type="Carrito" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TagArticulos" Member="TagArticulos">
    <Type Name="TagArticulo">
      <Column Name="idArticulo" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="idCloudItem" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="CloudItem_TagArticulo" Member="CloudItem" ThisKey="idArticulo" OtherKey="id" Type="CloudItem" IsForeignKey="true" />
      <Association Name="Articulo_TagArticulo" Member="Articulo" ThisKey="idArticulo" OtherKey="id" Type="Articulo" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CloudItems" Member="CloudItems">
    <Type Name="CloudItem">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="weight" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="url" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="tooltip" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="idUsuario" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="CloudItem_TagArticulo" Member="TagArticulos" ThisKey="id" OtherKey="idArticulo" Type="TagArticulo" />
      <Association Name="Usuario_CloudItem" Member="Usuario" ThisKey="idUsuario" OtherKey="id" Type="Usuario" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Articulos" Member="Articulos">
    <Type Name="Articulo">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="idCategoria" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="precio" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="imagen" Type="System.String" DbType="NChar(500)" CanBeNull="true" />
      <Association Name="Articulo_ArtCant" Member="ArtCants" ThisKey="id" OtherKey="idArticulo" Type="ArtCant" />
      <Association Name="Articulo_Registro" Member="Registros" ThisKey="id" OtherKey="idArticulo" Type="Registro" />
      <Association Name="Articulo_Calificacion" Member="Calificacions" ThisKey="id" OtherKey="idArticulo" Type="Calificacion" />
      <Association Name="Articulo_Interno" Member="Interno" ThisKey="id" OtherKey="id" Type="Interno" Cardinality="One" />
      <Association Name="Articulo_Externo" Member="Externo" ThisKey="id" OtherKey="id" Type="Externo" Cardinality="One" />
      <Association Name="Articulo_TagArticulo" Member="TagArticulos" ThisKey="id" OtherKey="idArticulo" Type="TagArticulo" />
      <Association Name="Categoria_Articulo" Member="Categoria" ThisKey="idCategoria" OtherKey="id" Type="Categoria" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Campos" Member="Campos">
    <Type Name="Campo">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="idPlantilla" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="tipo" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Association Name="Campo_Registro" Member="Registros" ThisKey="id" OtherKey="idCampo" Type="Registro" />
      <Association Name="Plantilla_Campo" Member="Plantilla" ThisKey="idPlantilla" OtherKey="id" Type="Plantilla" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Categorias" Member="Categorias">
    <Type Name="Categoria">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="idSuperCategoria" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="idPlantilla" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Categoria_Articulo" Member="Articulos" ThisKey="id" OtherKey="idCategoria" Type="Articulo" />
      <Association Name="Categoria_Categoria" Member="Categorias" ThisKey="id" OtherKey="idSuperCategoria" Type="Categoria" />
      <Association Name="Categoria_Categoria" Member="Categoria1" ThisKey="idSuperCategoria" OtherKey="id" Type="Categoria" IsForeignKey="true" />
      <Association Name="Plantilla_Categoria" Member="Plantilla" ThisKey="idPlantilla" OtherKey="id" Type="Plantilla" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Usuarios" Member="Usuarios">
    <Type Name="Usuario">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="login" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="esAdmin" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Association Name="Usuario_Cliente" Member="Cliente" ThisKey="id" OtherKey="id" Type="Cliente" Cardinality="One" />
      <Association Name="Usuario_CloudItem" Member="CloudItems" ThisKey="id" OtherKey="idUsuario" Type="CloudItem" />
    </Type>
  </Table>
  <Table Name="dbo.Carritos" Member="Carritos">
    <Type Name="Carrito">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="fechaCompra" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="montoTotal" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="idFormaPago" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="token" Type="System.String" DbType="NChar(100)" CanBeNull="true" />
      <Column Name="estado" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Carrito_Cliente" Member="Clientes" ThisKey="id" OtherKey="idCarritoActual" Type="Cliente" />
      <Association Name="Carrito_ArtCant" Member="ArtCants" ThisKey="id" OtherKey="idCarrito" Type="ArtCant" />
      <Association Name="Carrito_HistoricoCarrito" Member="HistoricoCarritos" ThisKey="id" OtherKey="idCarrito" Type="HistoricoCarrito" />
      <Association Name="FormaPago_Carrito" Member="FormaPago" ThisKey="idFormaPago" OtherKey="id" Type="FormaPago" IsForeignKey="true" />
    </Type>
  </Table>
</Database>