// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JSR-172 Reference Implementation wscompile 1.0, using: JAX-RPC Standard Implementation (1.1, build R59)

package edu.tsi4.truco.data.comm.ws;


public class Enviar {
    protected java.lang.String in0;
    protected java.lang.String in1;
    protected java.lang.String in2;
    
    public Enviar() {
    }
    
    public Enviar(java.lang.String in0, java.lang.String in1, java.lang.String in2) {
        this.in0 = in0;
        this.in1 = in1;
        this.in2 = in2;
    }
    
    public java.lang.String getIn0() {
        return in0;
    }
    
    public void setIn0(java.lang.String in0) {
        this.in0 = in0;
    }
    
    public java.lang.String getIn1() {
        return in1;
    }
    
    public void setIn1(java.lang.String in1) {
        this.in1 = in1;
    }
    
    public java.lang.String getIn2() {
        return in2;
    }
    
    public void setIn2(java.lang.String in2) {
        this.in2 = in2;
    }
}
