// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JSR-172 Reference Implementation wscompile 1.0, using: JAX-RPC Standard Implementation (1.1, build R59)

package edu.tsi4.truco.data.comm.ws;


public class RecibirResponse {
    protected java.lang.String out;
    
    public RecibirResponse() {
    }
    
    public RecibirResponse(java.lang.String out) {
        this.out = out;
    }
    
    public java.lang.String getOut() {
        return out;
    }
    
    public void setOut(java.lang.String out) {
        this.out = out;
    }
}
