// This class was generated by 172 StubGenerator.
// Contents subject to change without notice.
// @generated

package edu.tsi4.truco.data.comm.ws;

public interface Truco_PortType extends java.rmi.Remote {
	public edu.tsi4.truco.data.comm.ws.EnviarResponse enviar(java.lang.String in0, java.lang.String in1, java.lang.String in2) throws java.rmi.RemoteException;

	public java.lang.String recibir(java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException;

}
