package edu.tsi1.gr5.crazyfinger.pared.entity;

// Generated 03-oct-2009 15:52:18 by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;

import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

import edu.tsi1.gr5.crazyfinger.entity.Usuario;
import edu.tsi1.gr5.crazyfinger.media.entity.Media;

/**
 * Pared generated by hbm2java
 */
@Entity
@Table(name = "pared")
public class Pared implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 3880637242447615600L;
	
	private long idPared;
	private Usuario usuario;
	private String titulo;
	private Set<Media> medias = new HashSet<Media>(0);

	public Pared() {
	}

	public Pared(long idPared, Usuario usuario, String titulo) {
		this.idPared = idPared;
		this.usuario = usuario;
		this.titulo = titulo;
	}

	public Pared(long idPared, Usuario usuario, String titulo,
			Set<Media> medias) {
		this.idPared = idPared;
		this.usuario = usuario;
		this.titulo = titulo;
		this.medias = medias;
		
	}

	@GeneratedValue
	@Id
	@Column(name = "id_pared", unique = true, nullable = false)
	public long getIdPared() {
		return this.idPared;
	}

	public void setIdPared(long idPared) {
		this.idPared = idPared;
	}

	@OneToOne(fetch=FetchType.LAZY, mappedBy="pared")
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	@Column(name = "titulo", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getTitulo() {
		return this.titulo;
	}

	public void setTitulo(String titulo) {
		this.titulo = titulo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pared")
	public Set<Media> getMedias() {
		return this.medias;
	}

	public void setMedias(Set<Media> medias) {
		this.medias = medias;
	}


}
